### ISSUE TITLE
Multiple bugs with cost and weight modifiers for equipment

### ISSUE THREAD

**Issue by dec-00** [gcsga/gcsga#104]
There are multiple bugs with cost and weight modifiers for equipment:
* Subtraction does not work for cost or weight modifiers. _-100_, _-10%_ and _-0.5 CF_ gives the same results as _+100_, _+10%_ and _+0.5 CF_ respectively.
* The cost modifier settings of _"to original cost"_, "_to final base cost"_ and "_to final cost_" apply their cost modification even when inactive/unchecked.
* "Cost Adjustment" and "Weight Adjustment" in the table for equipment modifiers on a piece of equipment are blank even when they shouldn't be. Example image below (also demonstrates the previous two bugs):
![image](https://github.com/gcsga/gcsga/assets/118613102/a0e26f57-92f2-4b68-8aab-3388012b9708)
* The only weight modifier setting that seems to work is _"to original weight"_. The other three settings seem to be non-functional in my testing.
* Additive or subtractive weight modifiers should correct to _"x lb"_ if the units given are invalid, as in GCS. Right now, if you input a number by itself without following it with _lb_, the weight modifier won't do anything. Following the number with a nonsense unit (_"+x asdf"_ for example) calculates the weight as if it were _lb_, but will still display the nonsense unit instead of correcting it to _lb_. Some other units seem supported in both GCS and GCSGA such as _kg_ (simplified to 2 lb per 1 kg) and _g_, so you should ensure to not break these units when fixing this issue.
* Similar to the previous point, additive and subtractive cost modifiers when using the "_to base cost_" setting should auto correct to _"x CF"_. They already calculate as if this is the case, but they don't display as CF.

**Comment by rinickolous** [comment]
Issues 1-4 have been addressed. 5-6 require some major restructuring with how various enums for the system are handled. Currently in progress.
