### ISSUE TITLE
Using the 'Modifying Dice + Adds' rule seems to break damage calculation.

### ISSUE THREAD

**Issue by PrinceOfIonia** [gcsga/gcsga#11]
Hello! So, I've imported some characters into GCSGA, I noticed that when toggling the "Modifying Dice + Adds" rule the damage listings on some of the attacks seem to be in very long decimals, and I can't even roll them anymore.

This only affected attacks with a positive damage modifier (within the normal rules), like 1d+1. It would remain unbroken if the attack had a negative or no damage modifier.

![image](https://github.com/gcsga/gcsga/assets/18065446/43de990c-7db3-4125-bbbd-2eba3991cccb)
This character has 15 ST, and here are their attacks WITHOUT the "Modifying Dice + Adds" option enabled.

![image](https://github.com/gcsga/gcsga/assets/18065446/43d7f9bc-1d1f-4742-97bb-7a1145260402)
Here is what happens when you enable the option. Notice how the attacks with no damage modifier did not break.

I'm unsure if I'm just being dumb and doing something wrong, or if this is broken. Cheers!

**Comment by rinickolous** [comment]
Fixed via #16
