### ISSUE TITLE
Character Creation

### ISSUE THREAD

**Issue by Tarrith** [gcsga/gcsga#138]
When creating a new Actor it does not appear until the page is refreshed.
When importing a new character sheet from GCS a message is displayed - "Import Error for [character]: defs is null"

![image](https://github.com/gcsga/gcsga/assets/23333805/00468a21-a795-44c1-9c01-22f6bb4165db)

![image2](https://github.com/gcsga/gcsga/assets/23333805/a6e2bf21-a97f-42a8-ad09-5c1a0f1fa123)

Tarrith

**Comment by rinickolous** [comment]
Fixed in latest version.
