### ISSUE TITLE
Wrong URLs on Foundry Packages List

### ISSUE THREAD

**Issue by Whompratt** [gcsga/gcsga#49]
On the GCS-GURPS packages page, here: [https://foundryvtt.com/packages/gcsga](https://foundryvtt.com/packages/gcsga)
The Project URL is listed as [github.com/_gscga_/gcsga](https://github.com/gscga/gcsga), where it should be [github.com/_gcsga_/gcsga](https://github.com/gcsga/gcsga).

**Comment by crnormand** [comment]
Tru dat!    Thanks, I'll fix it when I get home.

**Comment by Whompratt** [comment]
Happy to help :)

**Comment by rinickolous** [comment]
Fixed.
