### ISSUE TITLE
Damage Reduction does not work correctly with Blunt Trauma

### ISSUE THREAD

**Issue by PrinceOfIonia** [gcsga/gcsga#50]
Damage Reduction is supposed to divide all injury by a set value. However it appears the calculator ignores this when it comes to Blunt Trauma damage (it looks like its calculating it after Damage Reduction) which is inaccurate. 

1. To test this out, go into the damage calculator, and set the incoming damage to 20, and the damage type to cutting.
2. Set the DR to 20, and check the flexible box. 
3. Set the damage reduction value to 2. 

What should happen: Damage is completely negated to 0 by the Flexible DR, this means the Blunt Trauma rules are in effect. B379 says every 10 points of cutting damage deals 1 point of injury to the user. 2 points of injury are then dealt to us, however the injury is then divided by 2 from our Damage Reduction, making the resulting injury deal 1 damage instead.

What actually happens: The calculator ignores Damage Reduction and claims the character should take 2 injury.

**Comment by mjeffw** [comment]
![image](https://github.com/gcsga/gcsga/assets/7349413/121d5273-9091-4f41-9db8-1c1f11156613)

**Comment by mjeffw** [comment]
Should be in the next alpha release.
